version: "3.8"

services:
  recallsync-mcp:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    stdin_open: true
    tty: true
